name: openrpc-testgen

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.80.0

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build -r --bin katana
          mkdir -p bins
          cp ./target/release/katana bins/
      - uses: actions/upload-artifact@v4
        with:
          name: dojo-bins
          path: bins

  test:
    needs: build
    runs-on: arc-runner-set
    container:
      image: ghcr.io/dojoengine/dojo-dev:v1.0.2
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions/download-artifact@v4
        with:
          name: dojo-bins
          path: /tmp/bins
      - run: |
          export PATH=/tmp/bins:$PATH
          chmod +x /tmp/bins/katana
          
          /tmp/bins/katana &
          
          docker run --rm docker.io/uacias/katana-runner:v0.0.1
          
