name: v5

on:
  push:
    branches:
      - 'uacias/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.80.0

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libclang-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build katana
        run: |
          cargo build --release --bin katana -j16
          mkdir -p bins
          cp ./target/release/katana bins/

      - name: Upload katana binary
        uses: actions/upload-artifact@v4
        with:
          name: dojo-bins
          path: bins

  test:
    needs: build
    runs-on: arc-runner-set
    env:
      KATANA_ADDR: "127.0.0.1"
      PAYMASTER_PRIVATE_KEY: "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
      PAYMASTER_ACCOUNT_ADDRESS: "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
      UDC_ADDRESS: "0x41a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf"
      ACCOUNT_CLASS_HASH: "0x07dc7899aa655b0aae51eadff6d801a58e97dd99cf4666ee59e704249e51adf2"
    strategy:
      matrix:
        include:
          - suite: "katana"
            port: "5050"
          - suite: "katana-no-mining"
            port: "5051"
          - suite: "katana-no-fee"
            port: "5052"
          - suite: "katana-no-account-validation"
            port: "5053"
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libclang-dev git curl bash libssl-dev pkg-config

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Scarb via script
        run: |
          export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v 2.8.4
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache target directory
        uses: actions/cache@v3
        with:
          path: katana-runner/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('katana-runner/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Download katana binary
        uses: actions/download-artifact@v4
        with:
          name: dojo-bins
          path: /tmp/bins

      - name: Set permissions for katana
        run: |
          chmod +x /tmp/bins/katana

      - name: Start katana node for ${{ matrix.suite }}
        run: |
          /tmp/bins/katana \
            --http.port "${{ matrix.port }}" \
            --http.addr "${KATANA_ADDR}" \
            --silent \
            $( if [ "${{ matrix.suite }}" = "katana-no-mining" ]; then echo "--no-mining --dev"; fi ) \
            $( if [ "${{ matrix.suite }}" = "katana-no-fee" ]; then echo "--dev --dev.no-fee"; fi ) \
            $( if [ "${{ matrix.suite }}" = "katana-no-account-validation" ]; then echo "--dev --dev.no-account-validation"; fi ) \
            &

      - name: Checkout katana-runner repository
        uses: actions/checkout@v3
        with:
          repository: neotheprogramist/starknet-rpc-tests
          path: katana-runner

      - name: Scarb build
        run: |
          scarb build
        working-directory: katana-runner

      - name: Build openrpc-testgen-runner
        # Use -j16 to speed up cargo build
        run: |
          cargo build --release -j16 --features "katana katana_no_mining katana_no_fee katana_no_account_validation" -p openrpc-testgen -p openrpc-testgen-runner
        working-directory: katana-runner

      - name: Run ${{ matrix.suite }} Suite
        run: |
          URLS="http://${KATANA_ADDR}:${{ matrix.port }}"
          target/release/openrpc-testgen-runner \
            --urls "${URLS}" \
            --paymaster-account-address "${PAYMASTER_ACCOUNT_ADDRESS}" \
            --paymaster-private-key "${PAYMASTER_PRIVATE_KEY}" \
            --udc-address "${UDC_ADDRESS}" \
            --account-class-hash "${ACCOUNT_CLASS_HASH}" \
            --suite ${{ matrix.suite }}
        working-directory: katana-runner
